In [2]:
import pandas as pd
import numpy as np

In [3]:
excel_file = 'muskTweets.xls'
tweets = pd.read_excel(excel_file, names = ["tweet", "time", "size"])

In [4]:
len(tweets)

3216

In [5]:
tweets.head()

,tweet,time,size
0,@bigajm Yup :),2017-09-29 10:39:57,NaN
1,Part 2 https://t.co/8Fvu57muhM,2017-09-29 09:56:12,NaN
2,Fly to most places on Earth in under 30 mins a...,2017-09-29 09:19:21,NaN
3,RT @SpaceX: Supporting the creation of a perma...,2017-09-29 08:57:29,SpaceX
4,BFR will take you anywhere on Earth in less th...,2017-09-29 08:53:00,NaN

In [6]:
print(tweets.iloc[0,2])
print(tweets.iloc[1,2])
print(tweets.iloc[3,2])

nan
nan
SpaceX

In [7]:
for x in range(len(tweets)-1, -1, -1):
    currTweet = tweets.iloc[x,0]
    if ((currTweet[0]+currTweet[1]) == "RT"):
        tweets = tweets.drop(tweets.index[x])

In [8]:
tweets.head()

                                               tweet                time size
0                                     @bigajm Yup :) 2017-09-29 10:39:57  NaN
1                     Part 2 https://t.co/8Fvu57muhM 2017-09-29 09:56:12  NaN
2  Fly to most places on Earth in under 30 mins a... 2017-09-29 09:19:21  NaN
4  BFR will take you anywhere on Earth in less th... 2017-09-29 08:53:00  NaN
5  Mars City\nOpposite of Earth. Dawn and dusk sk... 2017-09-29 06:03:32  NaN

In [9]:
# testing length of tweets (length includes spaces)
print("Tweet in row 11:\n", tweets.iloc[11,0])
print("\nNum characters of tweet in row 11 =", len(tweets.iloc[11,0]))

Tweet in row 11:
 @El_Deano @Daimler @Jalopnik Yes, I did :)

Num characters of tweet in row 11 = 42

In [12]:
# Set size of tweets to small(s), medium(m), or large(l)
# small = 1-47 characters
# medium = 48-93 characters
# large = 94-140 characters

for i in range(len(tweets)):  
    if len(tweets.iloc[i,0]) < 48:
        tweets.iloc[i,2] = 's'
    if len(tweets.iloc[i,0]) >= 48:
        if len(tweets.iloc[i,0]) <= 93:
            tweets.iloc[i,2] = 'm'
    if len(tweets.iloc[i,0]) > 93:
        tweets.iloc[i,2] = 'l'
tweets

,tweet,time,size
0,@bigajm Yup :),2017-09-29 10:39:57,s
1,Part 2 https://t.co/8Fvu57muhM,2017-09-29 09:56:12,s
2,Fly to most places on Earth in under 30 mins a...,2017-09-29 09:19:21,l
4,BFR will take you anywhere on Earth in less th...,2017-09-29 08:53:00,m
5,Mars City\nOpposite of Earth. Dawn and dusk sk...,2017-09-29 06:03:32,l
6,Moon Base Alpha https://t.co/voY8qEW9kl,2017-09-29 05:44:55,s
7,Will be announcing something really special at...,2017-09-29 02:36:17,m
9,@kevinroose Just another day in the office,2017-09-28 22:44:16,s
10,@Fashionista_com @mayemusk Congrats Mom! I lov...,2017-09-28 07:53:52,m
12,Prev ideas for paying ~$10B dev cost incl. Kic...,2017-09-27 03:18:59,l
13,Headed to Adelaide soon to describe new BFR pl...,2017-09-27 03:03:12,l
14,"@El_Deano @Daimler @Jalopnik Yes, I did :)",2017-09-26 15:04:25,s
15,Good NYT article from several years ago about ...,2017-09-26 05:39:25,m
16,@AdrianZorrillaC Yes,2017-09-26 03:13:54,s
17,Simulation of how the SpaceX Interplanetary Sp...,2017-09-26 03:11:58,l
18,@Daimler Good,2017-09-25 21:33:27,s
19,Major improvements & some unexpected applicati...,2017-09-25 13:15:05,l
20,Presentation of @SpaceX Interplanetary Spacesh...,2017-09-25 13:12:44,l
21,@USATODAYmoney @NathanBomey That's not a lot o...,2017-09-24 22:31:24,l
23,@Its_Subhamk Don't give up if the cause is imp...,2017-09-20 19:25:08,l
24,"@JimHeaney Absolutely. Moreover, we expect to ...",2017-09-19 19:36:39,m
25,@Richwsadler Does my hivemind count as me?,2017-09-16 09:16:04,s
26,@Bobby_Gupta Def not ok. Just sent a reminder ...,2017-09-16 05:16:49,l
27,@rishabagrwl2013 In discussions with national ...,2017-09-16 03:28:05,l
28,@JayCruicks_ATC What if we just made a mini ve...,2017-09-16 03:19:49,m
29,@bonnienorman Of course :),2017-09-15 18:33:11,s
30,High res version at https://t.co/YysKftHhoz,2017-09-14 12:02:59,s
31,@jovanik21 Most of it,2017-09-14 12:02:36,s
32,Long road to reusabity of Falcon 9 primary boo...,2017-09-14 12:00:21,l
33,@simcrook @SmileSimplify Actually ... yes,2017-09-14 06:01:02,s
...,...,...,...
3180,@chrisbrandow @TEA_in_Space Yup or Douglas Air...,2012-12-12 19:40:48,l
3181,My big worry would be long (hopefully) term wh...,2012-12-12 19:35:07,l
3182,"SpaceX will go public at some point, as I thin...",2012-12-12 19:27:15,l
3183,@IntlManOfRealty Best to study some form of en...,2012-12-12 19:15:02,l
3184,Tesla articles 30 mins apart: This Stock is Sc...,2012-12-12 19:12:05,l
3186,Tesla was just approved for a full Class 1 Mas...,2012-12-11 04:54:30,l
3187,Told my kids (age 8 and 6) that we were going ...,2012-12-10 01:13:23,l
3188,Congrats to @dmetcalf for being the first to d...,2012-12-09 10:38:48,l
3189,Interesting possible answer to the Fermi Parad...,2012-12-05 07:20:41,m
3191,Am happy to report that Tesla was narrowly cas...,2012-12-04 06:40:56,l
3192,Uranium ore now available on Amazon! So much m...,2012-12-02 23:12:03,l
3193,@shervin Thanks Shervin!,2012-11-29 12:00:15,s
3195,"Can't put my finger on it, but for some reason...",2012-11-28 03:19:37,l
3196,But if humanity wishes to become a multi-plane...,2012-11-27 20:00:03,l
3197,"And, yes, I do in fact know that this sounds c...",2012-11-27 19:55:32,l
3198,"Millions of people needed for Mars colony, so ...",2012-11-27 19:48:23,l
3199,Short vid of the recent @SpaceX mission to the...,2012-11-25 03:53:51,m
3200,@cthorm SS Heart of Gold powered by the Infini...,2012-11-24 02:07:43,m
3201,My talk for the Royal Aeronautical Society is ...,2012-11-23 21:45:06,l
3202,Liam Neeson's Life's Too Short sketch is super...,2012-11-23 05:16:03,m
3204,On the plus side...?@newscientist: #Climate ch...,2012-11-22 18:32:13,l
3205,Gave a talk on energy and transport at Oxford ...,2012-11-22 17:55:04,m
3206,@Thomas_Tregner Exactly!,2012-11-21 07:14:07,s
3207,Love this picture of the Curiousity rover on M...,2012-11-21 05:01:08,l
3209,"Btw, I don't think Apple is doomed. Just won't...",2012-11-20 21:32:50,l
3210,Mass. judge denies auto dealers' demand to kil...,2012-11-20 21:22:29,l
3211,"@YOUSRC Amos's article was fair, but his edito...",2012-11-20 08:52:03,l
3212,These articles in Space News describe why Aria...,2012-11-20 08:38:31,l
3213,Was misquoted by BBC as saying Europe's rocket...,2012-11-20 08:30:44,l
3214,Just returned from a trip to London and Oxford...,2012-11-19 08:59:46,l

In [11]:
#conda create -n tensorflow_env tensorflow
 #   conda activate tensorflow_env

SyntaxError: invalid syntax (<ipython-input-11-ed1f42e400e0>, line 1)

In [19]:
# setting frequency count
y1 = 2012-11-19
y2 = 2012-11-20
for tweets in range(len(tweets)):
    if tweets(1) >= y1:
        if tweets << y2:
            count = count+1
    y1=y1+1
    y2=y2+1
    count += count
    arrayOfFrequency = count

TypeError: 'int' object is not callable